mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.178.183:8554/Streaming/Channels/101
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5

