mqtt:
  enabled: False

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.178.183:8554/Streaming/Channels/101 
          roles:
            - detect
